datavault/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

""" import from the overal project web site """
from .views import ASBHome, LogoView, HomeView

""" imports from the diffent apps """
from glossary.views import GlossaryHome, TermenRapport, TermDetails

from glossary.admin import glossary_admin 
from vault.admin import datavault_admin

app_name = "project"
urlpatterns = [
    path("",ASBHome.as_view(),name="asb_home")
    , path('home',HomeView.as_view())
    , path('glossary/', include('glossary.urls'))
    , path('datavault/',include('vault.urls'))
    , path('gl_admin', glossary_admin.urls)
    , path('dv_admin', datavault_admin.urls)
] + static(settings.STATIC_ROOT, document_root=settings.BASE_DIR)

glossary/urls.py
from django.urls import include, path

from .views import GlossaryHome, TermenRapport,TermDetails
from .admin import glossary_admin

app_name = "glossary"
urlpatterns = [
    path('',GlossaryHome.as_view(), name='glossary_home')
    # , path('admin/',glossary_admin.urls)
    , path('termen',TermenRapport.as_view(),name='termen')
    , path('<int:pk>/term_detail',TermDetails.as_view(),name='term_detail')        
]

vault/urls.py
from django.urls import include, path

from .views import DatavaultHome, HubsView, HubDetailsView, LinksView, LinkDetailsView, SatelliteView, SatelliteDetailsView
from .admin import datavault_admin

app_name = "datavault"
urlpatterns = [
    path('', DatavaultHome.as_view(), name="datavault_home") 
    , path('hubs', HubsView.as_view(), name="hub_list")
    , path('<int:pk>/hub_details', HubDetailsView.as_view(), name="hub_details")
    , path('links',LinksView.as_view(), name="link_list")
    , path('<int:pk>/link_details', LinkDetailsView.as_view, name="link_details")
    , path('satellites', SatelliteView.as_view, name="satellite_list")
    , path('<int:pk>/satellite_details',SatelliteView.as_view, name="satellite_details")
    , path('admin/',datavault_admin.urls) 
    # , path('datavault/admin',admin.site.urls)     
] 

datavault/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
#from django.core.files.storage import FileSystemStorage
from django.db import models
#from django.db.models import Q
#from django.forms import Form
from django.http import (FileResponse, HttpResponse, HttpResponseNotFound,
                         HttpResponseRedirect)
from django.shortcuts import render
from django.views.generic import DetailView, FormView, ListView, TemplateView

class ASBHome(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

class LogoView(TemplateView):
    template_name = "logo.html"

class HomeView(TemplateView):
    template_name = "home.html"

datavault/templates/aumc_base_report.html
{% extends 'base.html'%}
{% block content %}
    <div id="content-main">
        {% block table_of_contents %} {% endblock table_of_contents %}
        {% block report_contents %} {{ block.super }} {% endblock report_contents %}
    </div>
{% endblock content %}

datavault/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load i18n static %}    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.js"></script>
    {% block extrastyle %}
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/dashboard.css' %}" />
        <!-- link rel="stylesheet" type="text/css" href="{% static 'admin/css/aumc.css' %}" -->
    {% endblock extrastyle %}    
    <title>{% block title %}ASB Beheer{% endblock title %}</title>
</head>
<body>
    <div class="fixed-header" > 
        {% block header %}
        <a href="{% url 'asb_home' %}"><img src="{% static 'logo_aumc.svg' %}" width="400" align="left"/></a>
        {% endblock header%}
    </div> 
    <div class="navigation">
        {% block navigation %}
        {% endblock %}
    </div>
    <div class="container">
        <div class="contents">
            <div id="content-main">
                {% block table_of_contents %} {% endblock table_of_contents %}
                {% block report_contents %} {% endblock report_contents %}
                {% block content %}{% endblock content %}
            </div>
        </div>
    </div>    
</body>
</html>

datavault/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<title>Creating Fixed Header and Footer with CSS</title>
<style>
    /* Add some padding on document's body to prevent the content
    to go underneath the header and footer */
    body{        
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .container{
        width: 80%;
        margin: 0 auto; /* Center the DIV horizontally */
    }
    .fixed-header, .fixed-footer{
        width: 100%;
        position: fixed;        
        padding: 10px 0;
        color: #fff;
    }
    .fixed-header{
        top: 0;
        background: lightgray;
    }
    .fixed-footer{
        bottom: 0;
        background: lightgray;
    }    
    /* Some more styles to beutify this example */
    nav a{
        color: #fff;
        text-decoration: none;
        padding: 7px 25px;
        display: inline-block;
    }
    .container p{
        line-height: 40px; /* Create scrollbar to test positioning */
    }
</style>
</head>
<body>
    <div class="fixed-header">
        <img src="http://localhost:8080/logo_aumc.svg" width="300"/> 
        <div class="container">
            <nav>
                <a href="#">Home</a>
                <a href="#">About</a>
                <a href="#">Products</a>
                <a href="#">Services</a>
                <a href="#">Contact Us</a>
            </nav>
        </div>
    </div>
    <div class="container">
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Vestibulum id metus ac nisl bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet sagittis. In tincidunt orci sit amet elementum vestibulum. Vivamus fermentum in arcu in aliquam. Quisque aliquam porta odio in fringilla. Vivamus nisl leo, blandit at bibendum eu, tristique eget risus. Integer aliquet quam ut elit suscipit, id interdum neque porttitor. Integer faucibus ligula.</p>
        <p>Quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Ut tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio. Phasellus auctor velit at lacus blandit, commodo iaculis justo viverra. Etiam vitae est arcu. Mauris vel congue dolor. Aliquam eget mi mi. Fusce quam tortor, commodo ac dui quis, bibendum viverra erat. Maecenas mattis lectus enim, quis tincidunt dui molestie euismod. Curabitur et diam tristique, accumsan nunc eu, hendrerit tellus.</p>
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Vestibulum id metus ac nisl bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet sagittis. In tincidunt orci sit amet elementum vestibulum. Vivamus fermentum in arcu in aliquam. Quisque aliquam porta odio in fringilla. Vivamus nisl leo, blandit at bibendum eu, tristique eget risus. Integer aliquet quam ut elit suscipit, id interdum neque porttitor. Integer faucibus ligula.</p>
        <p>Quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Ut tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio. Phasellus auctor velit at lacus blandit, commodo iaculis justo viverra. Etiam vitae est arcu. Mauris vel congue dolor. Aliquam eget mi mi. Fusce quam tortor, commodo ac dui quis, bibendum viverra erat. Maecenas mattis lectus enim, quis tincidunt dui molestie euismod. Curabitur et diam tristique, accumsan nunc eu, hendrerit tellus.</p>
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Vestibulum id metus ac nisl bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet sagittis. In tincidunt orci sit amet elementum vestibulum. Vivamus fermentum in arcu in aliquam. Quisque aliquam porta odio in fringilla. Vivamus nisl leo, blandit at bibendum eu, tristique eget risus. Integer aliquet quam ut elit suscipit, id interdum neque porttitor. Integer faucibus ligula.</p>
        <p>Quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Ut tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio. Phasellus auctor velit at lacus blandit, commodo iaculis justo viverra. Etiam vitae est arcu. Mauris vel congue dolor. Aliquam eget mi mi. Fusce quam tortor, commodo ac dui quis, bibendum viverra erat. Maecenas mattis lectus enim, quis tincidunt dui molestie euismod. Curabitur et diam tristique, accumsan nunc eu, hendrerit tellus.</p>
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Vestibulum id metus ac nisl bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet sagittis. In tincidunt orci sit amet elementum vestibulum. Vivamus fermentum in arcu in aliquam. Quisque aliquam porta odio in fringilla. Vivamus nisl leo, blandit at bibendum eu, tristique eget risus. Integer aliquet quam ut elit suscipit, id interdum neque porttitor. Integer faucibus ligula.</p>
        <p>Quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Ut tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio. Phasellus auctor velit at lacus blandit, commodo iaculis justo viverra. Etiam vitae est arcu. Mauris vel congue dolor. Aliquam eget mi mi. Fusce quam tortor, commodo ac dui quis, bibendum viverra erat. Maecenas mattis lectus enim, quis tincidunt dui molestie euismod. Curabitur et diam tristique, accumsan nunc eu, hendrerit tellus.</p>
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Vestibulum id metus ac nisl bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet sagittis. In tincidunt orci sit amet elementum vestibulum. Vivamus fermentum in arcu in aliquam. Quisque aliquam porta odio in fringilla. Vivamus nisl leo, blandit at bibendum eu, tristique eget risus. Integer aliquet quam ut elit suscipit, id interdum neque porttitor. Integer faucibus ligula.</p>
        <p>Quis quam ut magna consequat faucibus. Pellentesque eget nisi a mi suscipit tincidunt. Ut tempus dictum risus. Pellentesque viverra sagittis quam at mattis. Suspendisse potenti. Aliquam sit amet gravida nibh, facilisis gravida odio. Phasellus auctor velit at lacus blandit, commodo iaculis justo viverra. Etiam vitae est arcu. Mauris vel congue dolor. Aliquam eget mi mi. Fusce quam tortor, commodo ac dui quis, bibendum viverra erat. Maecenas mattis lectus enim, quis tincidunt dui molestie euismod. Curabitur et diam tristique, accumsan nunc eu, hendrerit tellus.</p>
    </div>    
    <div class="fixed-footer">
        <div class="container">Copyright &copy; 2016 Your Company</div>        
    </div>
</body>
</html>

datavault/templates/index.html
{% extends "base.html" %}
{% block content %}
<ul>
    <li><a href="{% url 'glossary:glossary_home' %}">Bedrijfswoordenboek</a></li>
    <li><a href="{% url 'datavault:datavault_home' %}">Datavault</a></li>
</ul>
{% endblock %}

datavault/templates/logo.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
</head>
<body>
    <div class="container-fluid">
        <header>
            {% block header %}
            <img src="http://localhost:8080/logo_aumc.svg" />            
            {% endblock header%}
        </header>
        {% block navigation %}
        {% endblock %}
        <div class="contents">
            {% block content %}
            <p>Placeholder tekst in basis template. Vervang met contentsblock</p>
            {% endblock content %}
        </div>
    </div>
</body>

</html>